### ISSUE TITLE
Request clarification of use with multiple sub-domains.

### ISSUE THREAD

**Issue by CaptainMidnight** [Domain-Connect/DomainConnectDDNS#5]
Hi, could you please confirm if the DomainConnectDDNSUpdate service is capable of running undates to the same domain provider with multiple sub-domains pointing to the same IP address?

My case use, 2x sub-domains have been created with IONOS, both configured with this utility to point to the same IP address, using the same install procedures.

The 1st sub-domain (A record) is now listed as using 'External Service - Dynamic DNS' - IP address is correct
The 2nd sub-domain (A record) is still listsed as using an IPv4 address - nothing else?

I'm trying to troubleshoot and determine if this multiple sub-domain to the same IP address functionality has been previously tested?

**Comment by pawel-kow** [comment]
@CaptainMidnight I am afraid only Python client can handle more than one domain at a time.
If you plan to deal with subdomains you can configure one subdomain with the windows client and then add a CNAME to the rest of the domains pointing to the other one. This way all subdomains will be updated with the new IP.
