### ISSUE TITLE
DomainConnectDDNS-Windows does not support TLS 1.2

### ISSUE THREAD

**Issue by ocdtrekkie** [Domain-Connect/DomainConnectDDNS#7]
So I have a domain that has traditionally used Domain Connect to update it's external IP. And now I have a domain controller on that internal network, which uses that domain as it's domain. (This is a traditional way the Internet was expected to work: example.com on the Internet points to my location, host1.example.com is a machine at that network, etc.)

However, the problem I've hit is that the Domain Connect DDNS app won't let me set up Domain Connect again (saying "Domain does not support Domain Connect"), presumably because it's trying to talk to my local DNS provider instead of GoDaddy's. I added the `_domainconnect` CNAME on my internal DNS, but that didn't help.

So how do I get the public DNS updated when on a network with split brain DNS?

**Comment by pawel-kow** [comment]
@ocdtrekkie "Domain does not support Domain Connect" tells that the domain does not resolve `_domainconnect TXT` record from the host running the DynDNS client. When this record resolves correctly to an end-point of GoDaddy, the rest of the protocol should work just fine.
What is the output when running `dig TXT +short _domainconnect.<hereyourdomainname>` ?

**Comment by ocdtrekkie** [comment]
On Windows, but this should be equivalent, I assume?

```
nslookup -type=TXT _domainconnect.example.org

Non-authoritative answer:
_domainconnect.example.org   canonical name = _domainconnect.gd.domaincontrol.com
_domainconnect.gd.domaincontrol.com     text =

        "domainconnect.api.godaddy.com"
```

**Comment by pawel-kow** [comment]
@ocdtrekkie OK, it does not seem to be DNS-record related, but maybe the resolver stub in c# is doing some tricks.
Unfortunately I do not know that piece of code that well to help here.
@bdickson1-godaddy anyone from GD supporting this windows code for DynDNS?

**Comment by pawel-kow** [comment]
@ocdtrekkie did you try if you face the same issue running the python client on the same windows machine?

**Comment by bdickson1-godaddy** [comment]
Can you please do that command, but share the output for the real domain you are using that is split brain, rather than example.org? The real domain name is needed to understand what is happening on the inside of your domain, and what problem there is and/or potential solutions.

**Comment by ocdtrekkie** [comment]
That's the real output of the command, I just replaced my domain name when pasting to GitHub since it's public. The domain is my username dot org, and I guess the additional note is that I do set a subdomain in the subdomain field as well.

I also realized the lookup for _domainconnect isn't affected by my internal DNS... my internal DNS reflects the name of the subdomain, but the main domain is resolving out to the public Internet already.

**Comment by bdickson1-godaddy** [comment]
The problem being described is a bit nebulous/confusing.
You don't need to give the real name, it is fine to continue to use example.org.
What is not clear is the current contents of the zone (hosted at godaddy), including 
- the name of the object you want to update (e.g. what is the owner name for the A record that you want the DDNS to update)
- whether the subdomain you are referencing is delegated to you, and if so, how? I.e. what is the literal name of the subdomain in question, and do you have an NS record for it at godaddy?
- whether those two use the same name (is $hostname == $subdomainname)?
- Is the only thing you are trying to do here, use DDNS to change the A record for $hostname on the GoDaddy DNS zone? Or do you also want some record(s) within the subdomain changed as well?
- Are you trying to dynamically update the target of the delegation to be at an IP address that changes?
- What are the SOA and NS records for your subdomain, as seen on your internal DNS (presumably the domain controller)?

**Comment by ocdtrekkie** [comment]
I'll just post this stuff and delete the images so it's not here forever. Access to this thing is nearly nonexistent.

Okay, here's my GoDaddy DNS, including the domain, the A record I am trying to update (the IP there is currently wrong/outdated) and the _domainconnect record there. I am only trying to update that record there, for external DNS at GoDaddy to get updated.

[removed]

I think the split brain may be a red herring, because the domain controller's SOA/NS is for the subdomain, not the main domain, and hence, it wouldn't have any issues reaching the _domainconnect entry:

[removed]

And this is what I can confirm as well there:

[removed]

However:

[removed]

**Comment by bdickson1-godaddy** [comment]
So, here's what I think you actually want to be doing:
Set up an A record that will be used for the IP of the name server for your child zone.
Use a name that is NOT inside the child zone.
culp-ns1 A current.ip.address.here
Then, delegate the child zone to that name server:
culp NS culp-ns1
Then, in your DDNS thing, use only the Domain Name (leave the Sub Domain blank)
You MAY need to add culp-ns1 to the NS set on your domain controller (i.e. in addition to soji)

**Comment by ocdtrekkie** [comment]
I'm confused: I'm not trying to do anything with my internal DNS. I'm just trying to update the DNS record for the subdomain at GoDaddy. And I don't understand why the DomainConnectDDNS client says the domain isn't supported if it can read the _domainconnect record.

In fact, I *think* I can provably demonstrate the issue is not related to having an internal DNS at all: I have another domain on GoDaddy, with the default DNS when I bought it including the _domainconnect record: I get the same error.

**Comment by ocdtrekkie** [comment]
I also tested this with both the domain I use in my internal DNS, and this fresh domain (with no subdomain), on both a Windows Server 2019 domain controller, and a Windows 10 PC outside of my domain. So now I am kind of wondering the client just doesn't work anymore.

**Comment by bdickson1-godaddy** [comment]
Ignore last line of what I wrote above.
The name of your subdomain MUST be different from the A record, otherwise the lookups won't work correctly. Your internal DNS thinks the record in question is on your internal server, not on GoDaddy.
If you set up a DIFFERENT record name for the IP address, with ANY name other than culp, it should work.
You would then have an A record with a name that does not "collide" with the name of the subdomain.
As soon as there is a subdomain, the expectation is that there is an NS in the parent for the subdomain.
That (implicit or actual) NS record will occlude any other record types at that name, making it literally impossible to apply the template, or to even query for the A record.
(The "culp NS new-a-record-owner-name" on the parent domain is optional, if you don't want the subdomain to exist on the outside world)

**Comment by ocdtrekkie** [comment]
No A records anywhere on any DNS server match this:

[removed]

**Comment by bdickson1-godaddy** [comment]
Let's work on getting what you want to work. There may be more than one way to cause the error message you are seeing.

If you try the above, without the subdomain, are you able to get an access code?
Apologies if that is something you already said, I just want to be 100% sure whether or not the access code step works.
(I had understood the error to be when you were trying to use the access code to update the domain, i.e. after the access code had been generated.)

**Comment by ocdtrekkie** [comment]
The access code step does not work. Regardless of whether I set a subdomain or not.

**Comment by bdickson1-godaddy** [comment]
Do you have details on when you last successfully updated that IP using Domain Connect, even approximately (e.g. what year)?
I'll see if I can figure out what is going on once I have that info...

**Comment by bdickson1-godaddy** [comment]
Okay, I looked into the current status in our system.
I do see two different DDNS templates have been applied, one for subdomain "culp", one for subdomain "mapl".
The A record for mapl currently starts with "73", FYI.
I suggest removing one (or maybe both) of those templates, and removing the A record for "culp", and trying from the first step again. Try with subdomain of "culp-ns1", and let's see if we can get the DDNS auth code to work, and then try to use that code to add/update the A record for "culp-ns1".
If you think this is okay to do as diagnostic steps, let me know and I will remove the template(s).

**Comment by ocdtrekkie** [comment]
Off-hand, I do not. (My IP was very very stable until my ISP was recently acquired.) I am currently trying to poke around the app in Visual Studio and see if I can find something wrong with the code. It *reads* like sensible code to me.

The error I get is within the OAuthHelper module. I threw some debug checks to verify it gets the correct DomainConnect URL, crafts a request for the settings URL which is correct (and returns a reasonable looking JSON object from GoDaddy's server. Then I get a System.Net.WebException, which is thrown by the RestAPIHelper.

**Comment by bdickson1-godaddy** [comment]
The app/code itself isn't something we support, but I'll work with you to help debug, to whatever degree I can.
It sounds like the DC protocol piece is okay, which is good news.
It sounds like you are heading in the right direction for identifying the source of the error, at least.
Ping me if there is anything you want me to check on the GD system (e.g templates present or not, what subdomain value is used, etc.).

**Comment by ocdtrekkie** [comment]
I've found the fix, and it is that this app has bitrot (slightly). And doesn't report a useful error in this case.

I added a bunch of random Debug.WriteLine() commands out along the way trying to get some good error messages, and I got this: `The underlying connection was closed: An unexpected error occurred on a send`

Which led me here: https://docs.microsoft.com/en-us/answers/questions/362284/error-the-underlying-connection-was-closed-an-unex.html

This is missing:
`System.Net.ServicePointManager.SecurityProtocol = System.Net.SecurityProtocolType.Tls12;`

Adding it anywhere above the HTTP request (I placed it on line 23 on RestAPIHelper.cs) launches the OAuth flow, though it may be better if it's somewhere more global for the application.

**Comment by ocdtrekkie** [comment]
So I can probably prepare a pull request to update the app, since the release files just sit in the repo and aren't signed by anyone, I don't think there's anything that would prohibit me from doing a PR that includes both the fixed code and a built release, though I am not sure it'd be super kosher to post a binary from an outside contributor (such as myself).

@pawel-kow has touched this project code before it looks like, so I am guessing he could also build the release binaries? I can either test and submit a PR for just the code, if someone affiliated with DomainConnect and/or GoDaddy wants to build it, or I can submit a PR also including the fixed binaries, if nobody else wants to build it.

**Comment by arnoldblinn** [comment]
I'm lurking here.  I wrote this initially.  I've moved onto other projects (and companies).  But can help in a pinch.

**Comment by ocdtrekkie** [comment]
@arnoldblinn Compliments on your work, I think it's quite a pleasant little codebase. :)

I have opened #8 which includes the code changes to fix the issue, but not the binary release. I also noted this project doesn't technically appear to be open source licensed, which might be pleasant.

**Comment by arnoldblinn** [comment]
I appreciate the feedback, update, and compliment.

I'll merge this and update the binary at some point this weekend.
